kind: pipeline
type: docker
name: default

steps:
- name: testing
  image: alpine 
  commands:
  - echo "Hello from Drone" 
- name: coveralls
  image: lizheming/drone-coveralls
  settings:
    token:
      from_secret: coveralls_token
    files:
    - ./lcov.info
trigger:
  event: [ push, pull_request, tag ]
