kind: pipeline
type: docker
name: default

trigger:
  event:
   - pull_request
   - tag
   - push

steps:
- name: install
  pull: if-not-exists
  image: cypress/browsers:node14.15.0-chrome96-ff94
  commands:
  - npm install

- name: tests
  depends_on: ["install"]
  image: cypress/browsers:node14.15.0-chrome96-ff94
  commands:
    - npm run test

- name: lint
  depends_on: ["install"]
  image: cypress/browsers:node14.15.0-chrome96-ff94
  commands:
    - npm run lint

- name: coverage
  depends_on: ["install"]
  image: cypress/browsers:node14.15.0-chrome96-ff94
  commands:
  - npm run coverage
  environment:
    COVERALLS_REPO_TOKEN:
      from_secret: COVERALLS_REPO_TOKEN
